export type DraftOperationErrorCode =
  | "PATH_OUTSIDE_WORKSPACE"
  | "INVALID_OPERATION_ID"
  | "OPERATION_ALREADY_EXISTS"
  | "SOURCE_ARTIFACT_MISSING"
  | "SOURCE_ARTIFACT_INVALID"
  | "ARTICLE_NOT_APPROVED"
  | "APPROVAL_INVALID"
  | "APPROVAL_STALE"
  | "LINTER_ERRORS"
  | "ASSET_RIGHTS_NOT_APPROVED"
  | "ASSET_FILE_INVALID"
  | "BUILD_SOURCE_MISMATCH"
  | "LINT_SOURCE_MISMATCH"
  | "LINT_RENDER_MISMATCH"
  | "PREVIEW_SOURCE_MISMATCH"
  | "PREVIEW_RENDER_MISMATCH"
  | "PREVIEW_WECHAT_MISMATCH"
  | "BUILD_ARTIFACT_HASH_MISMATCH"
  | "SNAPSHOT_MISSING"
  | "SNAPSHOT_TAMPERED"
  | "PLAN_TAMPERED"
  | "PLAN_EXPIRED"
  | "ACCOUNT_CHANGED"
  | "MODE_CHANGED"
  | "CURRENT_SOURCE_CHANGED"
  | "OPERATION_NOT_PREPARED"
  | "INVALID_STATUS_TRANSITION"
  | "IDEMPOTENCY_ALREADY_SUCCEEDED"
  | "IDEMPOTENCY_IN_PROGRESS"
  | "IDEMPOTENCY_UNKNOWN_STATE"
  | "IDEMPOTENCY_PLAN_EXISTS"
  | "LEDGER_LOCKED"
  | "LEDGER_INVALID"
  | "EVENT_CHAIN_INVALID"
  | "SENSITIVE_OUTPUT_REJECTED"
  | "RECEIPT_TAMPERED"
  | "RECONCILIATION_NOT_ALLOWED"
  | "RECONCILIATION_REMOTE_ID_REQUIRED";

export class DraftOperationError extends Error {
  constructor(
    readonly code: DraftOperationErrorCode,
    message: string,
    readonly details: Record<string, unknown> = {},
  ) {
    super(message);
    this.name = "DraftOperationError";
  }
}
